# Generated by Django 3.1 on 2020-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('regiId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=80)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
