# Generated by Django 3.1 on 2020-10-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='subscriber',
            new_name='no',
        ),
    ]
