# Generated by Django 3.1 on 2020-10-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0003_entry_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrys', to=settings.AUTH_USER_MODEL),
        ),
    ]
